//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolCalc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolCalc.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StiSerializer version=&quot;1.02&quot; type=&quot;Net&quot; application=&quot;StiReport&quot;&gt;
        ///  &lt;Dictionary Ref=&quot;1&quot; type=&quot;Dictionary&quot; isKey=&quot;true&quot;&gt;
        ///    &lt;BusinessObjects isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;Databases isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;DataSources isList=&quot;true&quot; count=&quot;2&quot;&gt;
        ///      &lt;data Ref=&quot;2&quot; type=&quot;DataTableSource&quot; isKey=&quot;true&quot;&gt;
        ///        &lt;Alias&gt;data&lt;/Alias&gt;
        ///        &lt;Columns isList=&quot;true&quot; count=&quot;2&quot;&gt;
        ///          &lt;value&gt;expense,Статья_x0020_расхода,System.String&lt;/value&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DebitCreditTotal {
            get {
                return ResourceManager.GetString("DebitCreditTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StiSerializer version=&quot;1.02&quot; type=&quot;Net&quot; application=&quot;StiReport&quot;&gt;
        ///  &lt;Dictionary Ref=&quot;1&quot; type=&quot;Dictionary&quot; isKey=&quot;true&quot;&gt;
        ///    &lt;BusinessObjects isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;Databases isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;DataSources isList=&quot;true&quot; count=&quot;2&quot;&gt;
        ///      &lt;data Ref=&quot;2&quot; type=&quot;DataTableSource&quot; isKey=&quot;true&quot;&gt;
        ///        &lt;Alias&gt;data&lt;/Alias&gt;
        ///        &lt;Columns isList=&quot;true&quot; count=&quot;2&quot;&gt;
        ///          &lt;value&gt;expense,Статья_x0020_расхода,System.String&lt;/value&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StiSerializer version=&quot;1.02&quot; type=&quot;Net&quot; application=&quot;StiReport&quot;&gt;
        ///  &lt;Dictionary Ref=&quot;1&quot; type=&quot;Dictionary&quot; isKey=&quot;true&quot;&gt;
        ///    &lt;BusinessObjects isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;Databases isList=&quot;true&quot; count=&quot;0&quot; /&gt;
        ///    &lt;DataSources isList=&quot;true&quot; count=&quot;1&quot;&gt;
        ///      &lt;data Ref=&quot;2&quot; type=&quot;DataTableSource&quot; isKey=&quot;true&quot;&gt;
        ///        &lt;Alias&gt;data&lt;/Alias&gt;
        ///        &lt;Columns isList=&quot;true&quot; count=&quot;4&quot;&gt;
        ///          &lt;value&gt;scholar,Ученик,System.String&lt;/value&gt;
        ///          &lt;va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarDebt {
            get {
                return ResourceManager.GetString("ScholarDebt", resourceCulture);
            }
        }
    }
}
